// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCk0gt_AMPwNQyjqu7ptJttnIBWQ2ux98w',
    appId: '1:468511516897:web:cb9905ff20393e64672fa0',
    messagingSenderId: '468511516897',
    projectId: 'travel-app-1bd2f',
    authDomain: 'travel-app-1bd2f.firebaseapp.com',
    storageBucket: 'travel-app-1bd2f.firebasestorage.app',
    measurementId: 'G-8QV1PEERSQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBSm8fyEkF4Jik5k36tNP6gZzCYRV6pvVQ',
    appId: '1:468511516897:android:6c20dfca15f27923672fa0',
    messagingSenderId: '468511516897',
    projectId: 'travel-app-1bd2f',
    storageBucket: 'travel-app-1bd2f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCe7akPYCGkF4n7cgfS3NdSy_V159ajJfc',
    appId: '1:468511516897:ios:3c2713d9e0438f8a672fa0',
    messagingSenderId: '468511516897',
    projectId: 'travel-app-1bd2f',
    storageBucket: 'travel-app-1bd2f.firebasestorage.app',
    iosBundleId: 'com.example.travel2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBF9ALO9jf1TGsoXxsdKB6HB6yEEnUCDJA',
    appId: '1:308105564646:ios:6f6866a3249cf248d58627',
    messagingSenderId: '308105564646',
    projectId: 'travel2-24f09',
    storageBucket: 'travel2-24f09.appspot.com',
    iosBundleId: 'com.example.travel2.RunnerTests',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCk0gt_AMPwNQyjqu7ptJttnIBWQ2ux98w',
    appId: '1:468511516897:web:c94fbb226d5d5cea672fa0',
    messagingSenderId: '468511516897',
    projectId: 'travel-app-1bd2f',
    authDomain: 'travel-app-1bd2f.firebaseapp.com',
    storageBucket: 'travel-app-1bd2f.firebasestorage.app',
    measurementId: 'G-57708K34NB',
  );

}